### ISSUE TITLE
INPUT_FILE_NAME is required to run MobSF action

### ISSUE THREAD

**Issue by kakumanivrn** [inm-certi/mobsf-action#3]
Error output: `INPUT_FILE_NAME is required to run MobSF action. (INPUT_FILE_NAME = /tmp/src_code.zip)`

Command:
```
- name: Run MobSF Analysis
   uses: inm-certi/mobsf-action@v1.3
      env:
        INPUT_FILE_NAME: /tmp/src_code.zip
        SCAN_TYPE: zip
        OUTPUT_FILE_NAME: mobsf-report
```

File `/tmp/src_code.zip` does exist and still the scan is failed.

![image](https://user-images.githubusercontent.com/4201693/92660418-a576e600-f2fa-11ea-9ca2-41523ca36b67.png)
